#ifndef HYPERPARAMETERS_H
#define HYPERPARAMETERS_H

#define LEAKY_RELU_LEAK 0.01
#define SWISH_BETA 1.0

#define LEARNING_RATE 0.002
#define ADAMW_WEIGHT_DECAY 0.001
#define ADAMW_BETA_MOMENTUM 0.8
#define ADAMW_BETA_VARIANCE 0.99
#define ADAMW_EPSILON 1e-8

#endif // HYPERPARAMETERS_H