#ifndef HYPERPARAMETERS_H
#define HYPERPARAMETERS_H

#define LEARNING_RATE 0.002
#define ADAMW_WEIGHT_DECAY 0.001
#define ADAMW_BETA_MOMENTUM 0.9
#define ADAMW_BETA_VARIANCE 0.999
#define ADAMW_EPSILON 1e-8

#endif // HYPERPARAMETERS_H